### ISSUE TITLE
Accordion Collapse

### ISSUE THREAD

**Issue by stevenbirr** [akserg/angular.dart.ui#130]
Hey guys,

we encountered a bug in the accordion component. We use the following markup for the accordion:
```
  <div class="modal-header">
    <h3 class="modal-title">Info-Overlay</h3>
  </div>
  <div class="modal-body">

    <accordion close-others="true">
      <accordion-group is-open="popup_message_controller.accordionIsOpen">
        <accordion-heading>
          Details
          <span class="pull-right glyphicon glyphicon-chevron-down"></span>
        </accordion-heading>
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata
      </accordion-group>
    </accordion>

  </div>
```

If you click once on the accordion header, it opens as expected. But if you click twice (e.g. accidentally), you get the Error 
**"angular.ui.collapse       Error on expand: Canceled".**
Every one-click afterwards causes the bug again, see the gif:
![accordion1](https://cloud.githubusercontent.com/assets/932159/4661985/189a640a-552b-11e4-91d1-a6b12bdd6e00.gif)

We ignored the bug until we used an accordion inside our Bootstrap-Overlays. Then we get a strange render bug as you can see in the following gif:
![accordion2](https://cloud.githubusercontent.com/assets/932159/4661986/1ca06982-552b-11e4-9f7e-22d8f4a54992.gif)

As you can see, the "Lorem Ipsum" text still appears, even if the accordion is closed!

**Comment by akserg** [comment]
Fixed in 0.6.5.

Can you confirm all you problems gone?
