### ISSUE TITLE
Chrome unable to find index.dart.js

### ISSUE THREAD

**Issue by digitalgym** [akserg/angular.dart.ui#145]
Chrome Version 40.0.2214.111 seems to be ignoring the .js externsion for resource http://akserg.github.io/angular.dart.ui.demo/build/index.dart.js on the demo page as aresult demo page does not work.

**Comment by akserg** [comment]
Quite strange. Here is my Chrome browser's version:
![image](https://cloud.githubusercontent.com/assets/1400409/6184285/92560cc2-b368-11e4-8d81-2e3426bcb13a.png)
And here the resulting page:
![image](https://cloud.githubusercontent.com/assets/1400409/6184309/f0585230-b368-11e4-9a15-deaea6217f8a.png)

**Comment by digitalgym** [comment]
I also get the page but console shows a 404 and components do not have styles or animation attached

**Comment by akserg** [comment]
Ok. Let me rebuild demo and push it again. I will let you.

**Comment by digitalgym** [comment]
I think its a chrome issue as demo site is fine in explorer.

**Comment by akserg** [comment]
On Firefox 34 and 35 it works as well.

**Comment by digitalgym** [comment]
iPhone chrome won't load 
iPad safari won't load
Mac chrome same issue can't load index.dart.js

**Comment by akserg** [comment]
The demo really out of date and must be updated. I will let you know.

**Comment by digitalgym** [comment]
Ok thanks appreciate it. The demo is really important when trying to sell dev treams on the product, the demo is the first thing they look at.

**Comment by akserg** [comment]
Agree.
