### ISSUE TITLE
Accordion: fast clicks on title causes inconstent state or bad rendering

### ISSUE THREAD

**Issue by Kaishiyoku** [akserg/angular.dart.ui#148]
Hello,

when I quickly click on a accordion's title bar repeatedly the accordion ends up in an inconsistent state. I guess this is caused by the collapse animation decorator.

When I click so fast and often the div container's padding is not being displayed properly, it looks like the accordion's content drops out of the accordion container.

A possible solution would be to disable the click handling as long as the animation lasts.

**Comment by stevenbirr** [comment]
I guess, this issue is related to this one: https://github.com/akserg/angular.dart.ui/issues/130

**Comment by akserg** [comment]
Yes, you are right. 
My apologies for this unreal delay. Fix it shortly.

**Comment by akserg** [comment]
Fixed in 0.6.5.

Can you confirm all you problems gone?

**Comment by akserg** [comment]
Fixed.
