### ISSUE TITLE
Carousel error -> slides are one below the other

### ISSUE THREAD

**Issue by Roba1993** [akserg/angular.dart.ui#150]
Hey Sergey,

The Carousel is not working in my Angular Dart Project. I've done everything I can image to fix it. The Alert element is working without any errors.

The single slides of the Carousel are displayed one below the other. The paging through the single slides with the small arrows on each side is also not working.

I hope you can help me.

![bildschirmfoto 2015-02-25 um 15 44 19](https://cloud.githubusercontent.com/assets/1376958/6372549/4b1c5090-bd05-11e4-9bac-bb5147f1d9bd.png)

**Comment by akserg** [comment]
Hi,

Did you added `slide.css` in you html file? Check this [link](https://github.com/akserg/angular.dart.ui/blob/master/web/index.html#L13).

**Comment by Roba1993** [comment]
Thank you!

Of course, this was the problem....
I really like your project, but in my opinion a short tutorial oder getting startet would be really helpful. I can create one for you. Simple say if you prefer it in the wiki or as readme.

**Comment by akserg** [comment]
Hi Robert,
I would really appreciated if you will help us in creating a short tutorials on wiki. Would you like to create  wiki page only for Carousel component or for all other components as well?

**Comment by Roba1993** [comment]
I would create one quick start page in general for all components. There I describe how to configure angular ui. Especially the points with the css, which is nowhere written down.

After that, I would create single pages for each component and I would start with the carousel. The rest of the components I am adding later, because at the moment my time is a bit limited. For the component wiki pages I would use a lot of the example content from your ui demo.

I ask me tonight, why you are separating the silde.css and why you aren't include them to the angular.css?

**Comment by akserg** [comment]
Each component's folder has README.md file with content showing in UI Demo. Can you update and use them?

About silde.css - that's a legacy style file we used before. Sounds it's time to fix this issue in current [release](https://github.com/akserg/angular.dart.ui/issues/151).
