### ISSUE TITLE
Accordion collapsed after initialisation with delay

### ISSUE THREAD

**Issue by stevenpietzsch** [akserg/angular.dart.ui#154]
Currently the accordion is expanded after initialisation and then shortly afterwards collapsed with a short delay (when isOpen=false). See example here: https://github.com/stevenbirr/angular-ui.dart.accordion-example

**Comment by akserg** [comment]
Is that problem?

**Comment by stevenbirr** [comment]
Of course it it. The default behaviour of accordion UI components is the initial collapse of closed parts, see here: http://www.tutorialrepublic.com/codelab.php?topic=bootstrap&file=accordion
As a user, you don't want to see a closing animation on page load.

**Comment by akserg** [comment]
Fear enough. 
I will fix it.

**Comment by stevenbirr** [comment]
Thank's a lot!

**Comment by akserg** [comment]
Fixed in 0.6.13
