### ISSUE TITLE
Is it time to create an angular2_ui package on https://pub.dartlang.org ?

### ISSUE THREAD

**Issue by sandrobilbeisi** [akserg/angular.dart.ui#163]
Hello all,

i was dabbling with the angular2 branch and tried grafting the angular.dart.ui.demo content when I realised that we still don't have an angular2_ui package on https://pub.dartlang.org

Do you think it's time to create it, or should we keep testing with local pub imports ?

**Comment by ronlobo** [comment]
:+1: for a new repo

**Comment by sandrobilbeisi** [comment]
:wink: A brand new repo by @akserg has just appeared: https://github.com/akserg/angular2.ui

:clap:  Good work, Sergei !

interestingly, it does not follow the naming pattern of the previous **angular.dart.ui**
the list of packages is slowly growing on https://pub.dartlang.org/search?q=angular

**Comment by zoechi** [comment]
Dart in the name doesn't make much sense, pub only hosts Dart packages

**Comment by akserg** [comment]
Exactly.
