### ISSUE TITLE
Typeahead highlight only works with the exact match need it to show highlight based on the words

### ISSUE THREAD

**Issue by shashank-v** [akserg/angular.dart.ui#171]
Is there a way I can pass in an a regular expression to the typeahead highlight formatter . I understand that regex is being escaped in the typeahead-highlight.dart . I pulled up the code and modified the typeahead_highlight.dart to accept a regular expression. I want to u to understand if there is a simpler way to do it
![screen shot 2016-07-27 at 7 24 26 pm](https://cloud.githubusercontent.com/assets/20703758/17214204/692ad0f0-54f5-11e6-935d-b68ccf50302b.png)

**Comment by akserg** [comment]
Hi @shashank-v 
Where is the code? Can you make a PR?

**Comment by shashank-v** [comment]
for the above scenario I just took the search string and build a pipe delimiter separated regular expression.

I can create a PR if this is acceptable

part of angular.ui.typeahead;

@Formatter(name : 'highlight')
class TypeaheadHighlightFilter implements Function {

  escapeRegexp(String queryToEscape) {
    var result = queryToEscape.replaceAllMapped(new RegExp(r'([.?*+^$[\]\\(){}|-])'), (Match m)=> '\\${m[0]}');
    return result;
  }

  String call(String matchItem, String query) {
    if (query == null || query.isEmpty) {
      return matchItem;
    } else {
      var queryArray = escapeRegexp(query).split(" ");
      StringBuffer queryString = new StringBuffer();
      if (queryArray.length > 1) {
        queryString.writeAll(queryArray,'|');
      } else {
        queryString.write(queryArray[0]);
      }
      return ('$matchItem')
          .replaceAllMapped(new RegExp(
          queryString.toString().trim(), caseSensitive: false), (
          Match m) =>  '<strong>${m[0]}</strong>');
    }
  }
}

**Comment by akserg** [comment]
I see you have created you own Formatter. Do you need any changes in angular.dart.ui framework?

**Comment by shashank-v** [comment]
I was thinking if this can be replaced with the existing typeahead_highlight.dart  and there would be no further changes required. This should work for all scenarios

**Comment by akserg** [comment]
Ok, I get it now. 
To be honest - I didn't update the angulat.dart.ui for a while. If you think your changes must be here - make a PR, update unit tests and we go.

**Comment by shashank-v** [comment]
Thank you very much , I will make the PR soon.

**Comment by akserg** [comment]
Sure, when you will have time.

**Comment by shashank-v** [comment]
@akserg  how do I get this to release version

**Comment by akserg** [comment]
I will release it.

**Comment by shashank-v** [comment]
@akserg  can u release it please

**Comment by akserg** [comment]
Hi @shashank-v 

Sorry, was really busy last week and weekend. Will do it today 100%

**Comment by shashank-v** [comment]
thank you very much!!!

**Comment by akserg** [comment]
The angular-ui 0.6.13 was published. Can you check and confirm that it works as expected?
https://pub.dartlang.org/packages/angular_ui

**Comment by akserg** [comment]
Hi @shashank-v 
Is that issue sorted out?

**Comment by shashank-v** [comment]
Thanks Sergey its all good thank you very much !!!
